#!/bin/bash

# Generate token - use swarm for service discovery
TOKEN=$(docker run --rm swarm create)

sed -i "/export TOKEN=/c\export TOKEN=$TOKEN" ./app_aws.env

# Initialise env variables
source ./app_aws.env

# Provision new machine
echo -e "
Provision machine for JMeter (Master):
docker-machine --debug create
    --driver amazonec2
    --amazonec2-access-key $AWS_ACCESS_KEY_ID
    --amazonec2-secret-key $AWS_SECRET_ACCESS_KEY
    --amazonec2-region $AWS_DEFAULT_REGION
    --amazonec2-vpc-id $AWS_VPC_ID
    --amazonec2-subnet-id $AWS_SUBNET_ID
    --amazonec2-zone $AWS_ZONE
    --amazonec2-ami $AWS_AMI
    --engine-label type=master
    --swarm
    --swarm-master
    --swarm-discovery token://$TOKEN
    jmeter-master"

docker-machine create \
    --driver amazonec2 \
    --amazonec2-access-key $AWS_ACCESS_KEY_ID \
    --amazonec2-secret-key $AWS_SECRET_ACCESS_KEY \
    --amazonec2-region $AWS_DEFAULT_REGION \
    --amazonec2-vpc-id $AWS_VPC_ID \
    --amazonec2-subnet-id $AWS_SUBNET_ID \
    --amazonec2-zone $AWS_ZONE \
    --amazonec2-ami $AWS_AMI \
    --engine-label type=master \
    --swarm \
    --swarm-master \
    --swarm-discovery token://$TOKEN \
    jmeter-master

echo "To manage swarm, make sure to run: eval \"\$(docker-machine env --swarm jmeter-master)\""
exit